"""
Report Generator — Generates downloadable PDF reports.

Converts the research output into a properly formatted PDF
that users can download and share.
"""

from datetime import datetime
from typing import Dict, List

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False


class ResearchReportPDF:
    """Generates a formatted PDF report from research results."""

    def generate(self, title: str, report_text: str, papers: list = None,
                 quality_score: float = 0.0, pipeline_info: dict = None) -> str:
        """
        Generate a PDF report and return the file path.
        
        Args:
            title: Research query / title
            report_text: The main research report markdown
            papers: List of papers found
            quality_score: Overall quality score
            pipeline_info: Info about paradigms used
        
        Returns: path to generated PDF file
        """
        if not HAS_FPDF:
            return self._generate_markdown_fallback(title, report_text, papers, quality_score)

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 20)
        pdf.cell(0, 15, "Deep Research Report", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

        # Query
        pdf.set_font("Helvetica", "I", 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, f"Query: {title[:80]}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(2)

        # Date and quality
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  "
                       f"Quality Score: {quality_score:.0%}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(3)

        # Paradigms used
        if pipeline_info:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(80, 80, 80)
            paradigms_text = "Paradigms: " + ", ".join(
                f"{s['name']} ({s['paradigm']})"
                for s in pipeline_info.get("steps", [])
            )
            pdf.cell(0, 6, paradigms_text[:120], new_x="LMARGIN", new_y="NEXT", align="C")

        # Divider
        pdf.ln(5)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(8)

        # Main report
        pdf.set_text_color(0, 0, 0)
        self._write_markdown(pdf, report_text)

        # Papers section
        if papers:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 16)
            pdf.cell(0, 12, "Papers Found", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

            for i, paper in enumerate(papers, 1):
                title_text = paper.title if hasattr(paper, "title") else str(paper)
                arxiv_id = paper.arxiv_id if hasattr(paper, "arxiv_id") else ""
                abstract = paper.abstract if hasattr(paper, "abstract") else ""

                pdf.set_font("Helvetica", "B", 11)
                pdf.multi_cell(0, 6, f"{i}. {self._clean(title_text)}")

                if arxiv_id:
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.set_text_color(50, 50, 200)
                    pdf.cell(0, 5, f"arXiv: {arxiv_id}", new_x="LMARGIN", new_y="NEXT")
                    pdf.set_text_color(0, 0, 0)

                if abstract:
                    pdf.set_font("Helvetica", "", 9)
                    pdf.multi_cell(0, 5, self._clean(abstract[:300]) + "...")

                pdf.ln(4)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 6, "Generated by Deep Research Agent | Adaptation of Agentic AI (Section 7.1)",
                 new_x="LMARGIN", new_y="NEXT", align="C")

        # Save
        output_path = f"reports/research_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        import os
        os.makedirs("reports", exist_ok=True)
        pdf.output(output_path)
        return output_path

    def _write_markdown(self, pdf, text: str):
        """Convert basic markdown to PDF formatting."""
        lines = text.split("\n")

        for line in lines:
            stripped = line.strip()

            if not stripped:
                pdf.ln(3)
                continue

            # Headers
            if stripped.startswith("### "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.multi_cell(0, 7, self._clean(stripped[4:]))
                pdf.ln(2)
            elif stripped.startswith("## "):
                pdf.set_font("Helvetica", "B", 14)
                pdf.multi_cell(0, 8, self._clean(stripped[3:]))
                pdf.ln(3)
            elif stripped.startswith("# "):
                pdf.set_font("Helvetica", "B", 16)
                pdf.multi_cell(0, 10, self._clean(stripped[2:]))
                pdf.ln(4)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                pdf.set_font("Helvetica", "", 10)
                pdf.cell(8, 6, chr(8226))  # bullet
                pdf.multi_cell(0, 6, self._clean(stripped[2:]))
            elif stripped.startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "9.")):
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 6, self._clean(stripped))
            else:
                pdf.set_font("Helvetica", "", 10)
                # Handle bold
                clean_text = self._clean(stripped)
                pdf.multi_cell(0, 6, clean_text)

    def _clean(self, text: str) -> str:
        """Clean text for PDF output — remove markdown formatting and non-latin chars."""
        import re
        text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)  # Remove bold markers
        text = re.sub(r"\*([^*]+)\*", r"\1", text)  # Remove italic markers
        text = re.sub(r"`([^`]+)`", r"\1", text)  # Remove code markers
        text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # Remove links
        # Replace non-latin1 characters
        text = text.encode("latin-1", errors="replace").decode("latin-1")
        return text

    def _generate_markdown_fallback(self, title, report_text, papers, quality_score) -> str:
        """Fallback: save as markdown if fpdf2 not available."""
        import os
        os.makedirs("reports", exist_ok=True)
        output_path = f"reports/research_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

        content = f"# Deep Research Report\n\n"
        content += f"**Query:** {title}\n\n"
        content += f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        content += f"**Quality Score:** {quality_score:.0%}\n\n---\n\n"
        content += report_text
        if papers:
            content += "\n\n---\n\n## Papers Found\n\n"
            for i, p in enumerate(papers, 1):
                t = p.title if hasattr(p, "title") else str(p)
                content += f"{i}. {t}\n"

        with open(output_path, "w") as f:
            f.write(content)
        return output_path
